### ISSUE TITLE
Class names

### ISSUE THREAD

**Issue by masquel** [nettofarah/react-flexible-switch#13]
Because of class names, when using with bootstrap, labels get `color:#fff` and become invisible.
To avoid this you should use bem style classes for example:

```
    .switch
    .switch--active
    .switch__label
    .switch__cirlce
```

or something else.

**Comment by lATAl** [comment]
@nettofarah I have the same issue

**Comment by nettofarah** [comment]
Just fixed it: https://github.com/nettofarah/react-flexible-switch#customzing-with-css-classes

Hope this helps you.
