### ISSUE TITLE
Add support to React 15.0.0

### ISSUE THREAD

**Issue by leandrooriente** [nettofarah/react-flexible-switch#7]

**Comment by nettofarah** [comment]
hi, @leandrooriente.
That sounds like a great idea.
I haven't tried with React 15 yet, but I can't see a reason why it wouldn't work.

Do you wanna take a stab at it and issue a PR?

**Comment by davojan** [comment]
Yes it would be great to get rid of

```
npm WARN react-flexible-switch@0.3.4 requires a peer of react@^0.14.0 but none was installed.
```

It works just fine with 15.2.1

**Comment by nettofarah** [comment]
alright! I'll look into this as soon as I can

**Comment by nettofarah** [comment]
Just released a new version of the library that fixes this issue.
